# Site
title: scottkillen.com
tagline: Scott Killen's blog
description: > # this means to ignore newlines until next key
  Scott Killen's blog
url: "https://scottkillen.com" # the base hostname & protocol for your site, e.g. http://example.com

author:
  name: Scott Killen
  twitter: scottkillen

twitter:
  username: scottkillen
  card: summary

logo: /assets/img/logo.png

social:
  name: Scott Killen
  links:
    - https://twitter.com/scottkillen
    - https://github.com/ScottKillen
    - https://dev.to/scottkillen
    - https://www.flickr.com/photos/scottkillen
    - https://www.instagram.com/scottdkillen/
    - https://www.deviantart.com/skillen

#Navbar links
navbar:
  links:
    - title: Poetry
      url: /poetry/
    - title: Gallery
      url: /gallery/
    - title: Tags
      url: /tags/

# Where things are
collections:
  pages:
    output: true
    permalink: /:name/
  photo_gallery:

# Handling Reading
exclude:
  - _artwork/
  - README.md

# Conversion
lsi: true

# Outputting
permalink: /:categories/:title/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
  - scope:
      path: "assets/img"
    values:
      image: true

# Plugin config
plugins:
  - jekyll-archives
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

jekyll-archives:
  enabled:
    - categories
    - tags
  permalinks:
    tag: "/tags/:name/"
    category: "/:name/"

feed:
  excerpt_only: true

paginate: 6
paginate_path: "/page/:num/"

redirect_from:
  json: false
