# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: scottkillen.com
tagline: Scott Killen's blog
description: > # this means to ignore newlines until next key
  Scott Killen's blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://scottkillen.com" # the base hostname & protocol for your site, e.g. http://example.com

author:
  name: Scott Killen
  email: scott@scottkillen.com
  picture: /assets/img/author.jpg
  twitter: scottkillen

twitter:
  username: scottkillen
  card: summary

logo: /assets/img/logo.svg

social:
  name: Scott Killen
  links:
    - https://twitter.com/scottkillen
    - https://github.com/scottkillen
    - https://dev.to/scottkillen
    - https://www.flickr.com/photos/scottkillen
    - https://www.instagram.com/scottdkillen/

#webmaster_verifications:
#  google: 1234
#  bing: 1234
#  alexa: 1234
#  yandex: 1234
#  baidu: 1234


navbar:
  brand: Navbar

footer:
  company-name: Company Name
  description: > # this means to ignore newlines until next key
    Company description or
    address.
  second-col-header: Products
  second-col-links:
    - name: Link 1
      url: /
    - name: Link 2
      url: /
    - name: Link 3
      url: /
    - name: Link 4
      url: /
  third-col-header: Useful Links
  third-col-links:
    - name: Link 1
      url: /
    - name: Link 2
      url: /
    - name: Link 3
      url: /
    - name: Link 4
      url: /
  contact:
    heading: Contact
    details:
      - <p><i class="fas fa-home mr-3"></i> New York, NY 10012, US</p>
      - <p><i class="fas fa-envelope mr-3"></i> info@gmail.com</p>
      - <p><i class="fas fa-phone mr-3"></i> + 01 234 567 88</p>
      - <p><i class="fas fa-print mr-3"></i> + 01 234 567 89</p>
  copyright: >
     © 2020 Copyright: <a href="/">
     <strong> Github User</strong></a>

paginate: 6
paginate_path: "/page/:num/"

# date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
date_format: "%b %-d, %Y"

  # generate social links in footer
social_links:
  twitter: scottkillen
  github:  scottkillen
  devto: scottkillen
  flickr:   scottkillen
  instagram: scottdkillen

  # Mastodon instances
  # mastodon:
  # - username: jekyll
  #  instance: example.com
  # - username: jekyll2
  #   instance: example.com

  # GitLab instances
  # gitlab:
  # - username: jekyll
  #  instance: example.com
  # - username: jekyll2
  #   instance: example.com

plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-paginate

include: ["_pages"]

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
